# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WoopSicredi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WoopSicredi
	pod 'Alamofire', '~> 4.0'
  	pod 'SwiftyJSON'
  	pod 'Kingfisher'
end
